### ISSUE TITLE
[Bug] template-output doesn't change from "test"

### ISSUE THREAD

**Issue by drjct** [mo-seph/obsidian-note-from-template#11]
Trying to save the new note to a specified folder but it won't take my input. 

<img width="490" alt="Screen Shot 2021-12-09 at 6 45 05 PM" src="https://user-images.githubusercontent.com/38368029/145508593-83dcd776-03b5-420a-aaa0-b128d8d442a5.png">
<img width="199" alt="Screen Shot 2021-12-09 at 6 45 25 PM" src="https://user-images.githubusercontent.com/38368029/145508621-c4522b01-cd12-44b5-9df0-2dce3e69453c.png">

**Comment by mo-seph** [comment]
This was originally set on workspace open, so wouldn't change when you updated the template. I've just refactored it all - see if the new version fixes it.
