### ISSUE TITLE
Does not read templates

### ISSUE THREAD

**Issue by brimwats** [mo-seph/obsidian-note-from-template#12]
I wanted to test this, so I made the ExampleTemplate in `000 - Landing Page. Inbox. KO. Meta/_Templates/testtemplate` and put that in settings
![image](https://user-images.githubusercontent.com/49103046/145557546-62da6c8a-a3d4-4e78-814c-dcb17f4ed1a7.png)

but it does not show up in the command palette
![image](https://user-images.githubusercontent.com/49103046/145557603-c054dd89-681c-490c-b84b-0f149b75678c.png)

**Comment by brimwats** [comment]
i tried it with the root slash too, so `/000 - Landing Page. Inbox. KO. Meta/_Templates/testtemplate`

**Comment by mo-seph** [comment]
Two possibilities:
- it looks like you have an old version - the current version should be listing the number of templates it has found in the directory, or giving an error
- did you reload Obsidian after changing the template directory? Unfortunately, this is currently necessary (although hopefully can be changed in a future version)

**Comment by mo-seph** [comment]
Have a try with the new version I've just pushed - that's changed a lot of things, and this should be a bit smoother.
