### ISSUE TITLE
[Feature Request] Modal -> Set Focus in the first field 

### ISSUE THREAD

**Issue by FelipeRearden** [mo-seph/obsidian-note-from-template#13]
Hello @mo-seph !!!!

This is a minor FR . I don’t know if is possible :)

When open the modal would bear amazing if the first field of the modal was already focused with the caret cursor ready to type. 
- today, aftrt biting the command, I have to type TAB to jump to the first field and start to write.

Today

![0](https://user-images.githubusercontent.com/85180696/145676068-4234dc93-74f6-486f-b3d4-0dce9b58575c.png)

My FR 

![1](https://user-images.githubusercontent.com/85180696/145676076-4f11c337-14ad-4888-ac6e-03ceb2cfa9bf.png)

---

Thanks :) 

Have a great day

**Comment by mo-seph** [comment]
Fixed in new version!

**Comment by FelipeRearden** [comment]
> Fixed in new version!

Thank you very much !!!!!!!!

Working perfect on version '0.1.6' Obsidian '0.12.19'
