### ISSUE TITLE
[Feature Request] Specific Modal div for a Full Screen CSS Snippet 

### ISSUE THREAD

**Issue by FelipeRearden** [mo-seph/obsidian-note-from-template#17]
Hello @mo-seph !!!!!

If possible :pray: I would like to ask for an specific modal name to the modal that From Template uses. 

![1](https://user-images.githubusercontent.com/85180696/151164427-df071ede-f7fc-45ef-8585-82b6b8f3971f.png)

My idea is to use a CSS snippet to create a Full Screen mode for the From Template mode !!!!1

I don´t have knowledge to explain the technical terms but this FR is the same that I created for the RSS Reader plugin
https://github.com/joethei/obsidian-rss/issues/51

If I have a specific modal, I can create a snippet to the Full Screen :)  

---

Thanks for reading this !

Have a great day!

**Comment by mo-seph** [comment]
Very sensible - I've just pushed a new version which sets the class 'from-template-modal' on the main modal

**Comment by FelipeRearden** [comment]
Thank you very much @mo-seph !!!!!

Please let me know when the new release is available:)

I wish you a fantastic day!!!!

**Comment by FelipeRearden** [comment]
Hello @mo-seph !!!!!

Thank you very much !!!!!

Working prefect on version 0.1.9 Obsidian 0.13.23

Have a great day!!!!!!
