### ISSUE TITLE
Multi-Select Dropdown Field Type

### ISSUE THREAD

**Issue by DevScribblesSomeWords** [mo-seph/obsidian-note-from-template#20]
Hi! I'm just getting started with using this plugin and am loving it so far particularly for my creative writing vault. One of the features I use the most is the choice type input but only one option can be picked. Can there be a multi-select input type so i can choose and display multiple options? 

My main use of the choice option is for tags [e.g. l/series or l/solo] where I only need to choose one option. But for my genre category I could need to add 2 or more tags [e.g. g/romance, g/comedy, g/drama] in one line. My current solution is just using a regular text input but the tag suggester is not shown.

Hope you can consider this. Great work on the plugin! ❤️

**Comment by mo-seph** [comment]
Added in 0.1.9 as `multi`, e.g. `{{colors:multi:yellow:red:green:blue}}`

**Comment by DevScribblesSomeWords** [comment]
That was fast! Thanks so much ❤️
