### ISSUE TITLE
Cannot add currentDate to template

### ISSUE THREAD

**Issue by Wizz4rrd** [mo-seph/obsidian-note-from-template#44]
I'd like that when a new page is made with a template, the date is added somewhere on the page. 
I can't get it working. 

I've tried adding {{date}}, {{now}}, {{currentDate}} and {{now:currentdate}} to YAML and in the note itself. 

What am I missing?

**Comment by slashk** [comment]
Try using 

```
{{Date:currentDate:MM-dd-yyyy}}
```

This works for me (you can change the `MM-dd-yyyy` to your preferred format.
