### ISSUE TITLE
Default regex in plugin setting does not work

### ISSUE THREAD

**Issue by Alega-ua** [mo-seph/obsidian-note-from-template#48]
> **template-input**
> If the command is called with some text selected, split it up using the plugin's split pattern, and put the values into those fields

Default regex in plugin setting does not work - it does not split the input into title and body
\s+-s+ 

<img width="784" alt="image" src="https://github.com/mo-seph/obsidian-note-from-template/assets/136184246/4fdcbe54-a5c5-4a5c-8c09-fb54d10d8529">

Template code
```
---
template-input: title, body
---
 
# {{title}}
{{body}}
```

**Comment by mo-seph** [comment]
It works here - what text did you have highlighted when you called the template?

**Comment by mo-seph** [comment]
BTW - it looks like your regex is missing a backslash - in the screenshot, it is `\s+-s+`, not `\s+-\s+`.

**Comment by Alega-ua** [comment]
\s+-s+ is the default value I have after installation - I changed nothing

**Comment by mo-seph** [comment]
I've just installed into a fresh vault, and I get the correct regex `\s+-\s+`. I'll try to keep an eye out for this, but unless I can reproduce it it's going to be hard to fix. I've updated the description in the settings to say what it *should* start out as in case someone else runs into the same thing.
