### ISSUE TITLE
Focus on the newly created note

### ISSUE THREAD

**Issue by Lulullia** [mo-seph/obsidian-note-from-template#6]
So far, when we run the command, it'll create the new note and fill it perfectly - but then we still need to open it manually which can be annoying.

It would be nice to have toggle in the settings to open the newly created note right after creation. It could work like QuickAdd's template options: whether to open it, if yes whether to open it in a new pane or on active pane, if in a new pane whether open it vertically or horizontally.

This would remove friction of having to manually find the file. It could also be another YAML key, to make it more flexible and decide which templates should open after creation and which ones shouldn't.

**Comment by mo-seph** [comment]
Agreed - both on the idea and the YAML execution

**Comment by mo-seph** [comment]
There's a new field in the new version: `template-should-create`, which you can use to open the new note in the same pane or a new split (vertical only at the moment0.

Can be set as a default, or by template in the YAML :)
