### ISSUE TITLE
[Feature Request] `Add`Button-> Keyboard Shortcut `CRTL/CMD+ENTER` to hit Add

### ISSUE THREAD

**Issue by FelipeRearden** [mo-seph/obsidian-note-from-template#9]
Hello @mo-seph !!!!! 

Would be amazing to have a keyboard shortcut to press the`Add` button !

My Suggestion is `CRTL/CMD+ENTER`

This way we can jump tp fill the fields with `TAB` and hit `CRTL/CMD+ENTER` and don't have to use the mouse !!!!

---

Thanks for reading!

Have a great day!

**Comment by mo-seph** [comment]
Agreed! Now I just need to figure out enough javascript/html to do it ;)

**Comment by FelipeRearden** [comment]
> Agreed! 

Great !!!!!! Thank you very much!!!!

> Now I just need to figure out enough javascript/html to do it ;)

Maybe the information below could be helpful :)

The Obsidian RSS Reader plugin https://github.com/joethei/obsidian-rss have a feature that you can define hotkey for the buttons inside a modal window 

Img

Img

---

Here is the FR -> https://github.com/joethei/obsidian-rss/issues/13

I hope it helps :) 

---

Have a great day!

**Comment by mo-seph** [comment]
New shortcuts added:
- Mod + enter: submit template
- Mod + (1-9): jump to field
- Ctrl + (1-9): select replacement string N if you have multiple values for `template-replacement`

**Comment by mo-seph** [comment]
Thanks for the link to the RSS plugin!

**Comment by FelipeRearden** [comment]
AMAZING !!!!!!!!

Thank you very much !!!!!!!!

Working perfect on version '0.1.6' Obsidian '0.12.19'

> Thanks for the link to the RSS plugin!

:+1:  :)
